---
title: "gtsummary in quarto"
format: html
theme: cosmo   # cosmo bootswatch theme
execute:
   echo: false
   message: false
---

```{r warning=FALSE, message=FALSE}

library(tidyverse)
library(gtsummary)

nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", 
               "id", "nsibs", "samp", "race_eth", "sex", "region", 
               "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |> 
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes"))) 
```

# Customization of `tbl_summary()`

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))
```

```{r}
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir),
  label = list(
    race_eth_cat ~ "Race/ethnicity",
    region_cat ~ "Region",
    eyesight_cat ~ "Eyesight",
    glasses ~ "Wears glasses",
    age_bir ~ "Age at first birth"
  ),
  missing_text = "Missing")
```

```{r}
#| label: tbl-one
#| tbl-cap: "this is a great table"
tableone <- tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))
```

**PRACTICE TEXT**
*this is for Quarto practice writing text*

-this should print on new line

@tbl-one has a table

```{r}
mean_sleep <- mean(nlsy$sleep_wknd, na.rm=TRUE)
print(mean_sleep)

median_sleep <- median(nlsy$sleep_wknd, na.rm=TRUE)
print(median_sleep)

#| label: tbl-two
#| tbl-cap: "this is a great table"
tabletwo <- tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir, sleep_wknd))
print(tabletwo)

inline_text(tabletwo, variable="sleep_wknd", column = "Male")
```

The mean number of hours of sleep on weekends was `r mean_sleep`

The mean number of hours of sleep on weekends was `mean(nlsy$sleep_wknd, na.rm=TRUE)`
```{r}
inline_text(tableone, variable="glasses", column = "Male")
```

```{r}
square <- function(x) {
	n <- length(x)
	square_val <- (x)^2
	return(square_val)
}

square(53)
53^2

power_of <- function(x, multiplier=3) {
	square_val <- (x)^multiplier 
	return(square_val)
}

power_of(x=5, multiplier=2)

new_table_function <- function(model) {
	tbl_regression(
		model,
		exponentiate = TRUE,
		label = list(
			sex_cat ~ "Sex",
			eyesight_cat ~ "Eyesight"
		)
	)
}

logistic_model <- glm(glasses ~ eyesight_cat + sex_cat,
											data = nlsy, family = binomial())

new_table_function(logistic_model)

```

